theme: jekyll-theme-minimal
logo: https://iut.uca.fr/uas/IUT63/LOGO_PIED/Logo_UCA-Institut-de-technologie_carre.png
title: Cours de dévelopement logiciel
description: BUT Science des données - Aurillac

