theme: jekyll-theme-minimal
logo: https://iut.uca.fr/uas/IUT63/LOGO_PIED/Logo_UCA-Institut-de-technologie_carre.png
title: BUT Science des données - Aurillac 
description: Cours de dévelopement logiciel du B.U.T Sciences des données.

navbar-text-col: "#007686"
link-col: "#007686"
hover-col: "#009AA0"